# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '18 8 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Your issue has not seen any activity in last 60 days, it has been marked as stale, make a new issue or mention someone for help.'
        stale-pr-message: 'Your pull request has not seen any activity in last 60 days, it has been marked as stale, update your PR or mention someone for help.'
        stale-issue-label: 'Stale'
        stale-pr-label: 'Stale'
        close-issue-message: 'Your issue has been closed as it has no activity in it. You can make a new issue anytime.'
        close-pr-message: 'Your pull request has been closed as it has no activity in it. You can make a new PR anytime.'
